### ISSUE TITLE
Unable to run dockerized SparkNLP

### ISSUE THREAD

**Issue by yy6linda** [nlpsandbox/phi-annotator-spark-nlp#57]
# Unable to run dockerized SparkNLP

Ran into a series of issues running docker-compose. Here documented the troubleshooting process and 1 remaining issue. SparkNLP is a commercialized tool. I have acquired a new license for running this tool.

### Replicate the error
1. Clone the repo 
2. Run "Docker compose up --build"
### Solutions
Changing `spark-nlp-jsl` to `spark-nlp` resolved this issue [code](https://github.com/nlpsandbox/phi-annotator-spark-nlp/blob/be71c58772d4007789493210a3bbceb4e37afc40/server/Dockerfile#L56)

### Replicate the error
1. Fix issue 1
2. Run "Docker compose up --build"
### Solutions
Going to [SparkNLP website](https://nlp.johnsnowlabs.com/models?task=Named+Entity+Recognition&language=en&q=phi) and updating the version of the NER model resolved this issue. [code](https://github.com/nlpsandbox/phi-annotator-spark-nlp/blob/be71c58772d4007789493210a3bbceb4e37afc40/.env.example#L6)

### Replicate the error
1.  Fix issue 1 and 2
2. Run "Docker compose up --build"
2. Go to the UI page, enter a sentence for annotation test. 
### Error details
<img width="1318" alt="Screen Shot 2022-02-01 at 11 20 48 AM" src="https://user-images.githubusercontent.com/39251215/152036402-8d80c346-a1ba-41df-bc2d-a5159243bb37.png">

### Expected behaviors
Annotate the test sentence and return PHI annotations.

**Comment by tschaffter** [comment]
@yy6linda If you just want to apply this tool to some data, you can use one of the following images:

- docker.synapse.org/syn22277124/phi-annotator-spark-nlp-ner-deid-large
- docker.synapse.org/syn22277124/phi-annotator-spark-nlp-ner-deid-synthetic

I placed these images in the private project `NLP Sandbox - Staging` because they include proprietary models. By default, Spark NLP requires a connection to their server, but I followed their instructions so that the models can be used offline.

For example, use the default `docker-compose.yml` from the `main` branch and the following commands to start the tool for the first model:

```
docker-compose pull
docker-compose up
```

Open your browser and navigate to http://localhost/ui to test the tool. Note that these Spark NLP models can take about ~40 seconds to initialize the first time you annotate a clinical note.

**Comment by yy6linda** [comment]
I ran the images previously. It broke after annotating ~50 notes with error **ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')** I can't do benchmarking using the images. Besides, we need to make sure the docker-compose works and can be reproduced. @tschaffter

**Comment by tschaffter** [comment]
Thanks for updating your post with the actual error message. You could try to increase the amount of memory made available to the container in [docker-compose.yml](https://github.com/nlpsandbox/phi-annotator-spark-nlp/blob/d9e8d30c60b9bf94ff987f68ed371e1352685548/docker-compose.yml#L31) and see if you can process more notes. If yes, it means that there is a memory leak somewhere in Spark or in the way Spark is used.

Regarding

> Changing spark-nlp-jsl to spark-nlp resolved this issue [code](https://github.com/nlpsandbox/phi-annotator-spark-nlp/blob/be71c58772d4007789493210a3bbceb4e37afc40/server/Dockerfile#L56)

Here you are replacing the private library by the public one, which is not what you want to do if you want to use a private model. You should be able to build the image if you specified your Spark license properly in `.env`.

**Comment by yy6linda** [comment]
I have "spark license specified properly" but It's not working with the error `spark-nlp-jsl not found`. Were you able to build docker image from scratch now? If so, please share with me the newly built docker images. The nginx implemented in the new version can resolve issue 3.  Same issue found in neuroner images and rebuilding the images resolved the issue.

**Comment by tschaffter** [comment]
> I have "spark license specified properly" but It's not working with the error spark-nlp-jsl not found.

I will send you by email how I used to set my license in `.env`. Just to give you an example.

> Were you able to build docker image from scratch now?

No, I don't have a valid license.

> The nginx implemented in the new version can resolve issue 3. Same issue found in neuroner images and rebuilding the images resolved the issue.

I used the neuroner image hosted on Synapse last week and it worked fine.

EDIT: I used the image in a different context, without using the `nginx` service defined in the `docker-compose.yml` file provided in the NLP Sandbox NeuroNER repository.

**Comment by yy6linda** [comment]
Thank you for sharing the example through the email. I specified the spark license the same way as you and the credentials were from the JSON file downloaded from sparkNLP after registration. Then ran into the errors mentioned at the top of the post.

**Comment by tschaffter** [comment]
In `.env`, try to set `SPARK_JSL_VERSION` to the version number included at the start of your `SPARK_NLP_LICENSE`.

```
SPARK_NLP_LICENSE=x.y.z-<more>
SPARK_JSL_VERSION=x.y.z
```
